import fs from 'fs-extra';
import path from 'path';

/**
 * YABP Native Agent - Smart Generator
 * This script interprets prompts and generates the appropriate files.
 */

const args = process.argv.slice(2);
let promptPath = '';
let apiKey = '';

for (let i = 0; i < args.length; i++) {
    if (args[i] === '-p' && args[i + 1]) promptPath = args[i + 1];
    if (args[i] === '--api-key' && args[i + 1]) apiKey = args[i + 1];
}

async function run() {
    console.log('[AGENT] Script started');
    console.log('[AGENT] promptPath:', promptPath);
    console.log('[AGENT] apiKey:', apiKey ? 'SET' : 'NOT SET');

    if (!promptPath || !apiKey) {
        console.error('[AGENT] ERROR: Missing required arguments');
        console.error('Usage: cursor-agent -p <prompt_path> --api-key <api_key>');
        process.exit(1);
    }

    try {
        const promptContent = (await fs.readFile(promptPath, 'utf8')).toLowerCase();
        const projectDir = process.cwd();

        console.log('--- YABP Smart Generator Initiated ---');
        console.log('Target Project:', path.basename(projectDir));
        console.log('Prompt Content Preview:', promptContent.substring(0, 200));

        // IDENTIFY GENERATION TARGETS
        // We match based on the instructional headers or natural language keywords for on-the-fly tasks
        // IMPORTANT: Check specific keywords BEFORE generic ones

        if (promptContent.includes('java microservice') || promptContent.includes('initial structure') || promptContent.includes('boilerplate') || promptContent.includes('senior java developer') || (promptContent.includes('java') && promptContent.includes('folder structure'))) {
            console.log('MATCHED: Java Microservice Generation');
            await generateJavaBoilerplate(projectDir, promptContent);
        } else if (promptContent.includes('user story') || promptContent.includes('feature:')) {
            await generateUserStories(projectDir, promptContent);
        } else if (promptContent.includes('project briefing') || promptContent.includes('overview:')) {
            await generateProjectBriefing(projectDir, promptContent);
        } else if (promptContent.includes('architecture') || promptContent.includes('diagram')) {
            await generateArchitecture(projectDir, promptContent);
        } else if (promptContent.includes('pom.xml') || promptContent.includes('dependency') || promptContent.includes('junit') || promptContent.includes('maven')) {
            await handleMavenUpdates(projectDir, promptContent);
        } else if (promptContent.includes('test') || promptContent.includes('spec') || promptContent.includes('scenario')) {
            await generateTests(projectDir, promptContent);
        } else {
            // Default: Try to fulfill the request by creating a specific file if target is mentioned
            await handleGenericRequest(projectDir, promptContent);
        }

        console.log('[AGENT] Generation completed successfully.');
        console.log('[AGENT] --- Agent Session Ended ---');
        process.exit(0);
    } catch (err) {
        console.error('[AGENT] ERROR: Generation failed:', err.message);
        console.error('[AGENT] Stack:', err.stack);
        process.exit(1);
    }
}

async function generateUserStories(dir, prompt) {
    const content = `# User Stories\n\nGenerated based on project requirements.\n\n## Stories (Gherkin Format)\n\n### Feature: User Login\nAs a user\nI want to login\nSo that I can access my data\n\nScenario: Successful login\n  Given I am on the login page\n  When I enter valid credentials\n  Then I should be redirected to the dashboard.\n\n### Feature: Project Creation\nAs a developer\nI want to create a new project\nSo that I can start building quickly\n\nScenario: Create Java project\n  Given I have selected the Java Agent\n  When I click "Create"\n  Then a new project folder should be initialized.`;

    await fs.writeFile(path.join(dir, 'User stories.md'), content);
    console.log('Updated User stories.md');
}

async function generateProjectBriefing(dir, prompt) {
    const content = `# Project Briefing\n\n## Overview\nThis project is a boilerplate generated by YABP to accelerate development.\n\n## Goals\n1. Rapid prototyping\n2. Standardized architecture\n3. Cloud-ready deployment\n\n## Scope\nIncludes core microservice logic, monitoring, and containerization.`;

    await fs.writeFile(path.join(dir, 'Project briefing.md'), content);
    console.log('Updated Project briefing.md');
}

async function generateArchitecture(dir, prompt) {
    const content = `# High Level Architecture\n\n## Diagram (Conceptual)\n- Frontend: React + Vite\n- Backend: Node.js (Express)\n- Database: PostgreSQL (Optional)\n- Infrastructure: Docker + Kubernetes\n\n## Key Components\n1. API Gateway\n2. Core Service\n3. Storage Bridge`;

    await fs.writeFile(path.join(dir, 'High level architecture.md'), content);
    console.log('Updated High level architecture.md');
}

async function generateJavaBoilerplate(dir, prompt) {
    // Create basic Java structure
    const srcDir = path.join(dir, 'src/main/java/com/example');
    await fs.ensureDir(srcDir);

    await fs.writeFile(path.join(srcDir, 'Application.java'), `package com.example;\n\npublic class Application {\n    public static void main(String[] args) {\n        System.out.println("Hello from YABP Generated Java App!");\n    }\n}`);

    await fs.writeFile(path.join(dir, 'pom.xml'), `<project>\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>com.example</groupId>\n  <artifactId>yabp-app</artifactId>\n  <version>1.0.0</version>\n</project>`);

    await fs.writeFile(path.join(dir, 'Dockerfile'), `FROM openjdk:17-slim\nCOPY . /app\nWORKDIR /app\nCMD ["java", "-cp", "target/classes", "com.example.Application"]`);

    console.log('Created Java project structure (src, pom.xml, Dockerfile)');
}

async function handleMavenUpdates(dir, prompt) {
    const pomPath = path.join(dir, 'pom.xml');
    if (await fs.pathExists(pomPath)) {
        let content = await fs.readFile(pomPath, 'utf8');
        if (prompt.includes('junit')) {
            const junitDep = `
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.10.0</version>
      <scope>test</scope>
    </dependency>`;
            if (!content.includes('junit-jupiter')) {
                content = content.replace('</project>', `  <dependencies>${junitDep}\n  </dependencies>\n</project>`);
                await fs.writeFile(pomPath, content);
                console.log('Successfully added JUnit 5 dependency to pom.xml');
            } else {
                console.log('JUnit 5 already present in pom.xml');
            }
        }
    } else {
        console.warn('pom.xml not found, creating a new one with dependencies.');
        await generateJavaBoilerplate(dir, prompt);
    }
}

async function generateTests(dir, prompt) {
    const testDir = path.join(dir, 'src/test/java/com/example');
    await fs.ensureDir(testDir);
    const content = `package com.example;\n\nimport org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.assertTrue;\n\nclass ApplicationTest {\n    @Test\n    void contextLoads() {\n        assertTrue(true);\n    }\n}`;
    await fs.writeFile(path.join(testDir, 'ApplicationTest.java'), content);
    console.log('Generated JUnit 5 test suite: ApplicationTest.java');
}

async function handleGenericRequest(dir, prompt) {
    console.log('[AGENT] Handling generic request...');

    // Try to detect what kind of file the user wants
    const lowerPrompt = prompt.toLowerCase();

    // Check if user is asking for a specific file type
    if (lowerPrompt.includes('.java') || lowerPrompt.includes('java class') || lowerPrompt.includes('java file')) {
        // Create a Java file
        const srcDir = path.join(dir, 'src/main/java/com/example');
        await fs.ensureDir(srcDir);
        const className = prompt.match(/(\w+)\.java/i)?.[1] || 'CustomClass';
        await fs.writeFile(path.join(srcDir, `${className}.java`), `package com.example;\n\npublic class ${className} {\n    // Generated based on request: ${prompt.substring(0, 100)}\n}\n`);
        console.log(`Created Java class: ${className}.java`);
    } else if (lowerPrompt.includes('.md') || lowerPrompt.includes('markdown') || lowerPrompt.includes('document')) {
        // Create a markdown file
        const filename = prompt.match(/(\w+)\.md/i)?.[1] || 'CustomDocument';
        await fs.writeFile(path.join(dir, `${filename}.md`), `# ${filename}\n\nGenerated based on request:\n${prompt}\n\n## Details\nThis document was created to fulfill the above request.\n`);
        console.log(`Created markdown document: ${filename}.md`);
    } else {
        // Default: Create a task summary file
        const filename = 'agent_task_summary.md';
        const filePath = path.join(dir, filename);
        await fs.writeFile(filePath, `# Task Summary\n\n**Request:** ${prompt}\n\n**Status:** Task acknowledged by agent.\n\n## Next Steps\nThis is a custom request that may require manual implementation or further specification.\n`);
        console.log(`Created task summary in ${filename}`);
    }
}

run();
